accounts/urls.py
from django.urls import path 
from . import views
app_name = "logins"
urlpatterns = [
    path('' , views.signIn , name="signin"),
    path('signup/' , views.signUp , name="signup"),
    path('logout/' , views.Logout_view , name="logout")
    #  path('profile/edit',views.profile_edit , name='profile_edit'),
]

blog/urls.py
from django.urls import path 
from . import views
app_name = "blogs"
urlpatterns = [
    path('', views.blog_post , name="blog"),
    path('single_blog/', views.single_blog_post , name="single_blog")
]

contact/urls.py
from django.urls import path 
from . import views
app_name = "contacts"
urlpatterns = [
    path('', views.contact , name="contact")
]

job/urls.py
from django.urls import path 
from . import views
app_name = "jobs"
urlpatterns = [
    path('',views.jobs , name="jobs"),
    path('add_job/',views.add_job , name='add_job'),
    path('<int:id_number>' , views.job_details , name="job_detail")
]

project/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("home.urls")),
    path('jobs/' , include("job.urls")),
    path('contact/' , include("contact.urls")),
    path('blog/' , include("blog.urls")),
    path('login/' , include("accounts.urls"))
    
]


if settings.DEBUG == True :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
JOBTYPE = (
    ('Full Time','Full Time'),
    ('Part Time','Part Time')
)
#class jobs
class Job(models.Model):
    owner = models.ForeignKey(User , related_name="owner_job", on_delete=models.CASCADE , blank=True , null=True)
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=100 , choices =JOBTYPE )
    description = models.TextField(max_length=400)
    published_at =  models.DateTimeField(auto_now=True)
    vecancy = models.IntegerField(default=1)
    salary = models.IntegerField()
    experiance = models.IntegerField(default=1)
    category = models.ForeignKey('Category' , on_delete=models.CASCADE)
    image = models.ImageField(upload_to="imageJob/" , blank=True , null= True)
    
    

    

    def __str__(self):
        return self.title



#class catefory
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name




class Apply(models.Model):
    name = models.CharField(max_length=50)
    email =  models.EmailField(max_length=254)
    website = models.URLField(max_length = 200 , blank=True , null=True)
    cv = models.FileField(upload_to='cvs', max_length = 100, blank=True , null=True)
    cover = models.TextField(max_length=260, blank=True , null=True)

    def __str__(self):
        return str(self.name)
    
    
    
    
    

job/views.py
from django.shortcuts import render
from .models import Job
from django.core.paginator import Paginator
from .filters import JobFilter
from .form import ApplyJob , AddJob
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def jobs(request):
    jobs = Job.objects.all()
    counter = jobs.count()
    #filter 
    myFilter = JobFilter(request.GET , queryset= jobs)
    jobs = myFilter.qs
    paginator = Paginator(jobs , 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"jobs":page_obj , "counter":counter , "myFilter":myFilter}
    return render(request , "job/jobs.html" , context)


def job_details(request , id_number):
    job_details = Job.objects.get(id=id_number)
    if request.method == "POST":
        form = ApplyJob(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            print('save')
            return HttpResponseRedirect(reverse('home:index'))
    else:
        form = ApplyJob()
    context = {"job_details":job_details , "form1":form}
    return render(request , "job/job_details.html" , context)




def add_job(request):
    if request.method == 'POST':
        form = AddJob(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('home:index'))
    else:
        form = AddJob(request.POST)
    return render(request , 'job/add_job.html' , {
        'form':form
    })

job/templates/job/add_job.html
{% extends "job/main.html" %}{% load bootstrap4 %} {% block body %}

<div style="margin-top:100px;" class="job_details_area">
    <div class="container">
        <div class="row">
            <h1>add Job</h1>
            <form method="POST">
                {% csrf_token %} {% bootstrap_form form %}
                <input type="submit" value="submit" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

job/templates/job/job_details.html
{% extends "job/main.html" %} {% load bootstrap4 %} {% block body %}

<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

<!-- header-start -->
<!-- header-end -->

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{ job_details.title }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#">
                                    <h4>{{job_details.title}}</h4>
                                </a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{ job_details.job_type }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>Job description</h4>
                        <p>{{ job_details.description }}</p>
                    </div>

                </div>
                <div class="apply_job_form white-bg">
                    <h4>Apply for the job</h4>
                    <form method="POST">
                        {% csrf_token %} {% bootstrap_form form1 %}
                        <input type="submit" value="submit" />
                    </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Published on: <span>{{ job_details.published_at }}</span></li>
                            <li>Vacancy: <span>{{ job_details.vecancy }} Position</span></li>
                            <li>Salary: <span>{{ job_details.salary }}k/y</span></li>
                            <li>Location: <span>California, USA</span></li>
                            <li>Job Nature: <span> {{ job_details.job_type }}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li>
                            <a href="#"> <i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa fa-envelope"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                                var uluru = {
                                    lat: -25.363,
                                    lng: 131.044
                                };
                                var grayStyles = [{
                                    featureType: "all",
                                    stylers: [{
                                        saturation: -90
                                    }, {
                                        lightness: 50
                                    }]
                                }, {
                                    elementType: 'labels.text.fill',
                                    stylers: [{
                                        color: '#ccdee9'
                                    }]
                                }];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    center: {
                                        lat: -31.197,
                                        lng: 150.744
                                    },
                                    zoom: 9,
                                    styles: grayStyles,
                                    scrollwheel: false
                                });
                            }
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- footer start -->
<!--/ footer end  -->

<!-- link that opens popup -->
<!-- JS here -->
{% endblock %}

job/templates/job/jobs.html
{% extends "job/main.html" %} {% load bootstrap4 %}{% block body %}

<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

<!-- header-start -->
<!-- header-end -->

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{ counter }} Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form method="GET">
                            {% csrf_token %} {% bootstrap_form myFilter.form %}
                            <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">

                        </form>
                    </div>

                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>
                            <div class="col-md-6">
                                <div class="serch_cat d-flex justify-content-end">
                                    <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for job in jobs %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        {% if job.image %}
                                        <img style="width:80px;height:70px;transform: translate(-12px , -12px);" src="{{ job.image.url }}" alt=""> {% endif %}
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'jobs:job_detail' job.id %}">
                                            <h4>{{ job.title }}</h4>
                                        </a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i> {{ job.job_type }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                        <a href="{% url 'jobs:job_detail' job.id %}" class="boxed-btn3">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <p>{{ job.published_at | date:'d M o' }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %} {% if jobs.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                        <li>
                                            <a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i> </a>
                                        </li>
                                        {% endif %} {% for i in jobs.paginator.num_pages %}
                                        <li><a href="?page={{i}}"><span>i</span></a></li>
                                        {% endfor %} {% if jobs.has_next %}
                                        <li>
                                            <a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

    <!-- footer start -->
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <!--contact js-->

    {% endblock %}

job/templates/job/main.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>


    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="{% static 'home:index' %}">
                                        <img src="{% static 'img/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'home:index' %}">home</a></li>
                                            <li><a href="{% url 'jobs:jobs' %}">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'blogs:blog' %}">blog</a></li>
                                                    <li><a href="single-blog.html">single-blog</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'contacts:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if user.is_authenticated %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logins:signin' %}">{{ request.user }}</a>
                                    </div>
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logins:logout' %}">Logout</a>
                                    </div>
                                    {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logins:signin' %}">Login</a>
                                    </div>
                                    {% endif %}
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>


    {% block body %} {% endblock %}

    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br> +10 873 672 6782 <br> 600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems luckily.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>
                                document.write(new Date().getFullYear());
                            </script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->

    <script src="{% static  'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static  'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static  'js/popper.min.js' %}"></script>
    <script src="{% static  'js/bootstrap.min.js' %}"></script>
    <script src="{% static  'js/owl.carousel.min.js' %}"></script>
    <script src="{% static  'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static  'js/ajax-form.js' %}"></script>
    <script src="{% static  'js/waypoints.min.js' %}"></script>
    <script src="{% static  'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static  'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static  'js/scrollIt.js' %}"></script>
    <script src="{% static  'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static  'js/wow.min.js' %}"></script>
    <script src="{% static  'js/nice-select.min.js' %}"></script>
    <script src="{% static  'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static  'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static  'js/plugins.js' %}"></script>
    <script src="{% static  'js/gijgo.min.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>