accounts/urls.py
from django.urls import path 
from . import views
app_name = "logins"
urlpatterns = [
    path('' , views.signIn , name="signin"),
    path('signup/' , views.signUp , name="signup"),
    path('logout/' , views.Logout_view , name="logout")
    #  path('profile/edit',views.profile_edit , name='profile_edit'),
]

blog/urls.py
from django.urls import path 
from . import views
app_name = "blogs"
urlpatterns = [
    path('', views.blog_post , name="blog"),
    path('single_blog/', views.single_blog_post , name="single_blog")
]

contact/urls.py
from django.urls import path 
from . import views
app_name = "contacts"
urlpatterns = [
    path('', views.contact , name="contact")
]

home/urls.py
from django.urls import path 
from . import views
app_name = "home"
urlpatterns = [
    path('' , views.home , name="index")
]

job/urls.py
from django.urls import path 
from . import views
app_name = "jobs"
urlpatterns = [
    path('',views.jobs , name="jobs"),
    path('add_job/',views.add_job , name='add_job'),
    path('<int:id_number>' , views.job_details , name="job_detail")
]

project/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("home.urls")),
    path('jobs/' , include("job.urls")),
    path('contact/' , include("contact.urls")),
    path('blog/' , include("blog.urls")),
    path('login/' , include("accounts.urls"))
    
]


if settings.DEBUG == True :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.


class Profile(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE , blank=True , null=True)
    phone_number = models.CharField(max_length=100)
    city = models.ForeignKey('City' , on_delete=models.CASCADE, blank=True , null=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=30)
    cover = models.TextField(max_length=300, blank=True , null=True)
    email = models.EmailField(max_length=100)
    image = models.ImageField(upload_to= "profile/")
    def __str__(self):
        return str(self.user)

@receiver(post_save , sender=User)
def create_user_profile(sender , instance , created , **kwargs):
    if created:
        Profile.objects.create(user=instance)


class City(models.Model):
    name = models.CharField(max_length=50, blank=True , null=True)
    def __str__(self):
        return self.name
    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreation(UserCreationForm):
    username = forms.CharField(label='username')
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label='password' , widget=forms.PasswordInput())
    password2 = forms.CharField(label='check the password password' , widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username' , 'email' , 'password1', 'password2']


class LoginForm(forms.ModelForm):
    username = forms.CharField(label="username")
    password = forms.CharField(label="password" , widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username' , 'password']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import LoginForm , UserCreation
# Create your views here.



def signIn(request):
    if request.method == 'POST':
        form = LoginForm()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request , username=username , password=password)
        if user is not None:
            login(request , user)
            return HttpResponseRedirect(reverse('home:index'))
    else:
        form = LoginForm()
    return render(request , 'accounts/signin.html' , {
        "form":form
    })


def signUp(request):
    if request.method == 'POST':
        form = UserCreation(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username= username , password=password)
            login(request , user)
            print('Create user')
            return HttpResponseRedirect(reverse('home:index'))
    else:
        form = UserCreation()
    return render(request , 'accounts/signUp.html' , {
        'userCreations':form
    })


def Logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))

accounts/templates/accounts/main.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'  %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>


    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="{% url 'home:index' %}">
                                        <img src="{% static 'img/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'home:index' %}">home</a></li>
                                            <li><a href="{% url 'jobs:jobs' %}">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'blogs:blog' %}">blog</a></li>
                                                    <li><a href="single-blog.html">single-blog</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'contacts:contact' %}">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    {% if user.is_authenticated %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logins:signin' %}">{{ request.user }}</a>
                                    </div>
                                    {% else %}
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="{% url 'logins:signin' %}">Login</a>
                                    </div>
                                    {% endif %}
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>


    {% block body %} {% endblock %}

    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br> +10 873 672 6782 <br> 600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems luckily.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>
                                document.write(new Date().getFullYear());
                            </script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->

    <script src="{% static  'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static  'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static  'js/popper.min.js' %}"></script>
    <script src="{% static  'js/bootstrap.min.js' %}"></script>
    <script src="{% static  'js/owl.carousel.min.js' %}"></script>
    <script src="{% static  'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static  'js/ajax-form.js' %}"></script>
    <script src="{% static  'js/waypoints.min.js' %}"></script>
    <script src="{% static  'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static  'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static  'js/scrollIt.js' %}"></script>
    <script src="{% static  'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static  'js/wow.min.js' %}"></script>
    <script src="{% static  'js/nice-select.min.js' %}"></script>
    <script src="{% static  'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static  'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static  'js/plugins.js' %}"></script>
    <script src="{% static  'js/gijgo.min.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %} 
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>

                            </ul>
                            
                        </div>
                        <div class="p-5">
                            <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}"> Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}





 

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %} 
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}
                            {% buttons %}
                                
                                <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}





 

accounts/templates/accounts/signUp.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>SignUp </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript">
        addEventListener("load", function() {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->
</head>

<body>
    <!-- main -->
    <div class="main-w3layouts wrapper">
        <h1> SignUp </h1>
        <div class="main-agileinfo">
            <div class="agileits-top">
                <form method="POST">
                    {% csrf_token %}<span>Enter the username</span> {{ userCreations.username }}<span>Enter the Email</span> {{ userCreations.email }} <span>Enter the password</span>{{ userCreations.password1 }} <span>Enter the password again</span> {{userCreations.password2}}
                    <div class="wthree-text">
                        <label class="anim">
							<input type="checkbox" class="checkbox" required="">
							<span>I Agree To The Terms & Conditions</span>
						</label>
                        <div class="clear"> </div>
                    </div>
                    <input type="submit" value="SIGNUP">
                </form>
                <p>Don't have an Account? <a href="{% url 'logins:signin' %}"> Login Now!</a></p>
            </div>
        </div>

        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
    <!-- //main -->
</body>

</html>

accounts/templates/accounts/signin.html
{% load static %} {% load bootstrap4 %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Log-in</title>

    <link rel='stylesheet' href='http://codepen.io/assets/libs/fullpage/jquery-ui.css'>
    <link rel="stylesheet" href="{% static 'css/sign.css' %}">
</head>

<body>

    <div class="login-card">
        <h1>Log-in</h1><br>
        <form method="POST">
            {% csrf_token %} {% bootstrap_form form %}
            <input type="submit" name="login" class="login login-submit" value="login">
        </form>

        <div class="login-help">
            <a href="{% url 'logins:signup' %}">Register</a> • <a href="#">Forgot Password</a>
        </div>
    </div>

    <!-- <div id="error"><img src="https://dl.dropboxusercontent.com/u/23299152/Delete-icon.png" /> Your caps-lock is on.</div> -->

    <script src='http://codepen.io/assets/libs/fullpage/jquery_and_jqueryui.js'></script>

</body>

</html>